[package]
name = "russia-ca-analyser"
version = "0.1.0"
edition = "2021"

[dependencies]
num_threads = "0.1.6"
openssl = "0.10.50"
threadpool = "1.8.1"

[profile.release]
opt-level = "z"
codegen-units = 1
panic = "abort"
lto = true
